name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: |
          echo HRKU-68033b81-292b-487f-b95c-610150d1d474 | heroku auth:token

      - name: Add Heroku remote
        run: |
          git remote add heroku https://git.heroku.com/peopley.git

      - name: Deploy to Heroku
        run: |
          git push heroku main
