name: Deploy to Heroku

on:
  push:
    branches:
      - main  # або ваша гілка для деплою

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Checkout коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v3  # Використовуємо останню версію actions/checkout

      # Крок 2: Встановлення Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Крок 3: Логін до Heroku за допомогою токена
      - name: Login to Heroku
        run: |
            echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token


      # Крок 4: Додавання віддаленого репозиторію Heroku
      - name: Add Heroku remote
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      # Крок 5: Деплой на Heroku
      - name: Deploy to Heroku
        run: |
          git push heroku main
